#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"
$LOAD_PATH << "controllers"
$LOAD_PATH << "views"

require 'expense'
require 'home'
Database.environment = ENV["ENVIRONMENT"] || "production"

HomeView.main
